<?php

/**
 * Confirmation token validator.
 *
 * Pure helper used by ConfirmationApiController and ConfirmationTokenService
 * to generate, hash and validate 32-character URL-safe confirmation tokens
 * for the appointment confirmation flow per REQ-BCF-002/004.
 *
 * Tokens are stored as salted bcrypt hashes (cost 12) — never plaintext.
 * Validation uses PHP's password_verify which is constant-time, so callers
 * cannot leak token bytes through timing side channels.
 *
 * @category Util
 * @package  OCA\Shillinq\Util
 *
 * @author    Conduction Development Team <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @link https://conduction.nl
 *
 * @spec openspec/changes/bookings-confirm-flow/tasks.md#task-17
 *
 * SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
 * SPDX-License-Identifier: EUPL-1.2
 */

declare(strict_types=1);

namespace OCA\Shillinq\Util;

use DateTimeImmutable;
use DateTimeZone;
use InvalidArgumentException;

/**
 * Side-effect-free generator + verifier for confirmation tokens.
 *
 * The class is intentionally small and dependency-free so it can be used
 * from both controller and background-job context with no DI ceremony.
 *
 * @spec openspec/changes/bookings-confirm-flow/tasks.md#task-17
 */
final class TokenValidator {

	/**
	 * Length, in characters, of the URL-safe token string generated by
	 * {@see TokenValidator::generate()}. Aligns with REQ-BCF-001 ("32-character
	 * random URL-safe string"). Using base62 means 32 chars carry ~190 bits of
	 * entropy — well in excess of the OWASP 64-bit minimum for short-lived
	 * authentication tokens.
	 */
	public const TOKEN_LENGTH = 32;

	/**
	 * Bcrypt cost used when hashing token strings for storage. Matches the
	 * design.md guidance ("bcrypt cost 12"). Higher cost would slow login-like
	 * validation without measurably improving security against a stolen DB
	 * dump on PHP 8.3 hardware.
	 */
	public const BCRYPT_COST = 12;

	/**
	 * Default token lifetime, in seconds. Used by callers that do not pass an
	 * explicit expiry — design.md D5 picks 7 days.
	 */
	public const DEFAULT_TTL_SECONDS = (7 * 24 * 60 * 60);

	/**
	 * Base62 alphabet used by {@see TokenValidator::generate()} — URL-safe (no
	 * `+`, `/`, or `=` padding so the token can be passed as a path segment
	 * or query parameter without encoding).
	 *
	 * @var string
	 */
	private const ALPHABET = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';

	/**
	 * Generate a fresh URL-safe random token string.
	 *
	 * @param int $length Number of characters to emit (defaults to 32).
	 *
	 * @return string A `$length`-character base62 string drawn from a
	 *                cryptographically-secure RNG.
	 */
	public static function generate(int $length = self::TOKEN_LENGTH): string {
		if ($length < 1) {
			$length = self::TOKEN_LENGTH;
		}

		$alphabetLength = (strlen(self::ALPHABET) - 1);
		$out = '';
		for ($i = 0; $i < $length; $i++) {
			$out .= self::ALPHABET[random_int(0, $alphabetLength)];
		}

		return $out;
	}//end generate()

	/**
	 * Hash a plaintext token for storage.
	 *
	 * The hash is salted by PHP automatically — callers MUST NOT prepend a
	 * static pepper.
	 *
	 * @param string $plaintext The plaintext token to hash.
	 *
	 * @return string The bcrypt hash, safe to store in
	 *                ConfirmationToken.tokenString.
	 */
	public static function hash(string $plaintext): string {
		return password_hash($plaintext, PASSWORD_BCRYPT, ['cost' => self::BCRYPT_COST]);
	}//end hash()

	/**
	 * Validate a presented token against a stored bcrypt hash.
	 *
	 * Uses PHP's password_verify which performs a constant-time comparison
	 * — callers cannot leak token bytes through timing analysis.
	 *
	 * @param string $plaintext The plaintext token presented by the customer.
	 * @param string $hash The bcrypt hash stored in
	 *                     ConfirmationToken.tokenString.
	 *
	 * @return bool TRUE iff the plaintext matches the hash, FALSE otherwise.
	 */
	public static function verify(string $plaintext, string $hash): bool {
		if ($plaintext === '' || $hash === '') {
			return false;
		}

		return password_verify($plaintext, $hash);
	}//end verify()

	/**
	 * Decide whether an `expiresAt` timestamp is in the past relative to
	 * `now`.
	 *
	 * Both timestamps are parsed via DateTimeImmutable so they must be
	 * ISO 8601 strings. Any parse failure is treated as expired (fail-closed
	 * — CWE-863).
	 *
	 * @param string $expiresAt Token expiration timestamp.
	 * @param string $now Reference "now" timestamp (typically
	 *                    ITimeFactory::getDateTime()->format(c)).
	 *
	 * @return bool TRUE iff the token has expired or expiresAt is unparseable.
	 */
	public static function isExpired(string $expiresAt, string $now): bool {
		try {
			$expiresDt = new DateTimeImmutable($expiresAt);
			$nowDt = new DateTimeImmutable($now);
		} catch (\Throwable $e) {
			// Fail closed: an unparseable timestamp is treated as expired.
			return true;
		}

		return ($expiresDt <= $nowDt);
	}//end isExpired()

	/**
	 * Build the ISO 8601 UTC `expiresAt` for a freshly-issued token from a
	 * given creation timestamp + TTL.
	 *
	 * @param string $createdAt ISO 8601 timestamp at which the token was created.
	 * @param int $ttlSeconds Token lifetime in seconds (defaults to 7 days).
	 *
	 * @return string ISO 8601 UTC `expiresAt` (suffix `Z`).
	 *
	 * @throws InvalidArgumentException When `$createdAt` is not parseable.
	 */
	public static function expiresAtFor(string $createdAt, int $ttlSeconds = self::DEFAULT_TTL_SECONDS): string {
		try {
			$dt = new DateTimeImmutable($createdAt, new DateTimeZone('UTC'));
		} catch (\Throwable $e) {
			throw new InvalidArgumentException('createdAt is not a valid ISO 8601 timestamp: ' . $createdAt, 0, $e);
		}

		$expires = $dt->modify('+' . max(0, $ttlSeconds) . ' seconds');
		return $expires->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d\TH:i:s\Z');
	}//end expiresAtFor()
}//end class
