name: Documentation

on:
  push:
    branches: [development, documentation]
  pull_request:
    branches: [development, documentation]

jobs:
  deploy:
    uses: ConductionNL/.github/.github/workflows/documentation.yml@main
    with:
      cname: shillinq.conduction.nl
